### PR TITLE
Feat Add Server Example

### PR DESCRIPTION
**Pull request by saulonunesdev**
Add Software to validate MIT License

### CODE REVIEW

**Comment by Trott** [comment]
> Add Software to validate MIT License

So we're adding some code so that the MIT license fits better?

**Comment by saulonunesdev** [comment]
yes @Trott

**Comment by Trott** [comment]
> yes @Trott

I'm not sure adding code because we're using the MIT license is the approach that we want to take here. If these are internal community docs, MIT license is fine. If it is external documentation, license should be switched to CC-BY-4.0.  https://github.com/nodejs/community-committee/issues/271#issuecomment-471488180

**Comment by saulonunesdev** [comment]
like on the  #184 its more easier to add some simple code to validade the license than find the specific license that applys to this initiative, What do yout think @Trott we could adress this on the next comcom meeting to see how to resolve this issue

**Comment by Trott** [comment]
It seems like this is adding irrelevant software to make the license "fit". I think we should either leave the license as is or update the license.

**Comment by davidguttman** [comment]
@Trott I figured it could be a good base for future work, but I take the point. I agree that we should leave the license as is. 👍

**Pull request closed without merging**
