### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by keywordnew**
Addresses: https://github.com/nodejs/community-committee/issues/559

Guidance by: https://github.com/nodejs/community-committee/issues/271#issuecomment-471488180

### CODE REVIEW

**Review by saulonunesdev — APPROVED** [review]
LGTM

**Comment by Trott** [comment]
There's no software in this repository. MIT license specifically is all about "this software". I'm not sure that's the right license for this.

**Comment by davidguttman** [comment]
> If the material is documentation intended to be provided to users, use the CC-BY-4.0. For internal community documents, use the MIT license.

@trott thinking that CC-BY is a better fit?

**Comment by Trott** [comment]
> > If the material is documentation intended to be provided to users, use the CC-BY-4.0. For internal community documents, use the MIT license.
> 
> @Trott thinking that CC-BY is a better fit?

I'll defer to @keywordnew and the Community Committee on this. Just mentioning that there's no software in this repository, so if that means MIT is not the appropriate license, then yeah, let's switch. It *seems* like MIT is an odd fit for non-software, given that MIT license text specifically says it's licensing software. But I am not a lawyer and I have no special expertise here. It's possible that I'm bad at this.

**Comment by davidguttman** [comment]
Happy to quickly add some software to make things easy ;)

**Pull request merged**
